Updated to include NVRTC DLLs

diff --git a/build b/build
--- a/build
+++ b/build
@@ -55,6 +55,7 @@ if [[ ! ${8} ]] ; then
 	echo "	Stage 4.2 - Oidn"
 	echo "	Stage 4.3 - C-blosc"
 	echo "	Stage 4.4 - TBB"
+	echo "	Stage 4.5 - NVRTC"
 	echo "	Stage 5   - luxcore"
 	echo "	Stage 6   - luxmark (optional)"
 	echo
@@ -479,7 +480,7 @@ if [[ $STAGE && $STAGE < $NEXT ]] ; then
 fi
 
 # STAGE 4.4 -- TBB
-NEXT=5
+NEXT=4.5
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
 	begin_stage TBB tbb*_lin.tgz
 
@@ -490,6 +491,24 @@ if [[ $STAGE && $STAGE < $NEXT ]] ; then
         echo " * TBB library and headers installed successfully"
     else
         echo " !!! TBB library and headers installation failed"
+        exit 1
+    fi
+
+	complete_stage $NEXT
+fi
+
+# STAGE 4.5 -- NVRTC
+NEXT=5
+if [[ $STAGE && $STAGE < $NEXT ]] ; then
+	begin_stage NVRTC cuda*nvrtc*.tar.gz
+
+	cp -v ${DIST}/nvrtc-install.sh .
+
+    sleep 1
+    if ./nvrtc-install.sh $TARGET ; then
+        echo " * NVRTC library installed successfully"
+    else
+        echo " !!! NVRTC library installation failed"
         exit 1
     fi
 
