Now Qt5 is compiled only if LuxMark has to be compiled too

diff --git a/build b/build
--- a/build
+++ b/build
@@ -410,19 +410,24 @@ fi
 # STAGE 3 -- Qt
 NEXT=4.1
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
+    if [[ ! -d "LuxMark" ]] ; then
+	echo
+	echo "LuxMark src not available, skipping the Qt stage"
+    else
 	begin_stage Qt qt-*.tar.gz
 
-#	cp -v ${DIST}/qt-install.sh .
-#
-#    sleep 1
-#    if ./qt-install.sh $TARGET ; then
-#        echo " * Qt library and headers installed successfully"
-#    else
-#        echo " !!! Qt library and headers installation failed"
-#        exit 1
-#    fi
+	cp -v ${DIST}/qt-install.sh .
 
-	complete_stage $NEXT
+	sleep 1
+	if ./qt-install.sh $TARGET ; then
+            echo " * Qt library and headers installed successfully"
+	else
+            echo " !!! Qt library and headers installation failed"
+            exit 1
+	fi
+    fi
+
+    complete_stage $NEXT
 fi
 
 # STAGE 4.1 -- Embree
