Removed OMP static linking, fixed LuxRays multithreaded compilation (patch by jensverwiebe)

diff --git a/build b/build
--- a/build
+++ b/build
@@ -95,9 +95,9 @@ fi
 
 # build flags
 GENERIC_FLAGS="$6"
-LUXRAYS_FLAGS=`echo $7 | sed s/'-fvisibility=hidden'//`" -fopenmp -pthread -lgomp -lrt"
+LUXRAYS_FLAGS=`echo $7 | sed s/'-fvisibility=hidden'//`" -pthread -lrt"
 LUXRAYS_OPTS="-D SLG_INCLUDE_DIRS='${WORK}/luxrays/samples/smallluxgpu' -D SLG_LIBRARY='${WORK}/luxrays/lib/libsmallluxgpu.a'"
-LUX_FLAGS="$7 -I${TARGET}/include -L${TARGET}/lib -fopenmp -pthread -lgomp -lrt"
+LUX_FLAGS="$7 -I${TARGET}/include -L${TARGET}/lib -pthread -lrt"
 
 # platform specs
 export CHOST="$8"
@@ -212,7 +212,7 @@ NEXT=1.2
 if [[ $STAGE && $STAGE < $NEXT ]] ; then
 	begin_stage boost boost*.tar.bz2
 
-	PYVER=`python --version 2>&1 | cut -d' ' -f2 | cut -d '.' -f'1 2'`
+	PYVER=`python3 --version 2>&1 | cut -d' ' -f2 | cut -d '.' -f'1 2'`
 	TOOLSET=`if [[ $CLANG ]] ; then echo clang ; else echo gcc ; fi`
 	echo " * Compiling boost for python-${PYVER}"
 	sleep 1
@@ -492,17 +492,18 @@ if [[ $STAGE && $STAGE < $NEXT ]] ; then
 	cp -vf ${DIST}/sattva-luxrays.cmake cmake/SpecializedConfig/sattva.cmake
 
 	echo " * Configuring $LUXRAYS_TARGET"
-	if ! cmake $DISABLE_OPENCL -Wno-dev -D LUXRAYS_CUSTOM_CONFIG=cmake/SpecializedConfig/sattva.cmake . ; then
+	if ! cmake -G "Unix Makefiles" $DISABLE_OPENCL -Wno-dev -D LUXRAYS_CUSTOM_CONFIG=cmake/SpecializedConfig/sattva.cmake . ; then
 		echo " !!! $LUXRAYS_TARGET configuration failed"
 		exit 1
 	fi
 	sleep $PAUSE
 	echo " * Compiling $LUXRAYS_TARGET"
-	if make $MAKEOPTS $LUXRAYS_TARGET ; then
-		echo " * $LUXRAYS_TARGET compiled successfully"
-	else
-		echo " !!! $LUXRAYS_TARGET compilation failed"
-		exit 1
+#	if make $MAKEOPTS $LUXRAYS_TARGET ; then
+    if cmake --build . --target pyluxcore -- $MAKEOPTS && cmake --build . --target luxcoreui -- $MAKEOPTS ; then
+        echo " * $LUXRAYS_TARGET compiled successfully"
+    else
+        echo " !!! $LUXRAYS_TARGET compilation failed"
+        exit 1
 	fi
 	sleep $PAUSE
 	cd $ROOT
